// lsu.v — load/store unit: byte/half/word select+extend on loads, position on stores
// Port names from core's perspective (guide Figure 2) — core_data_o/core_address_o/
// op_size_o/mem_data_o are LSU INPUTS. bw_o generated by control unit, not here.
// lb/lh sign-extend per guide §3.3.1 general rule (resolved over conflicting worked example).

module lsu (
    input  wire [31:0] core_data_o,
    input  wire [31:0] core_address_o,
    input  wire [2:0]  op_size_o,
    input  wire [31:0] mem_data_o,

    output reg  [31:0] core_data_i,
    output reg  [31:0] mem_data_i
);

    localparam [2:0] OP_SIZE_BYTE_S = 3'b000;
    localparam [2:0] OP_SIZE_BYTE_U = 3'b001;
    localparam [2:0] OP_SIZE_HALF_S = 3'b010;
    localparam [2:0] OP_SIZE_HALF_U = 3'b011;
    localparam [2:0] OP_SIZE_WORD   = 3'b100;

    wire [1:0] byte_sel = core_address_o[1:0];

    // Load path
    reg [7:0]  load_byte;
    reg [15:0] load_half;

    always @(*) begin
        load_byte = 8'b0;
        case (byte_sel)
            2'b00:   load_byte = mem_data_o[ 7: 0];
            2'b01:   load_byte = mem_data_o[15: 8];
            2'b10:   load_byte = mem_data_o[23:16];
            2'b11:   load_byte = mem_data_o[31:24];
            default: load_byte = mem_data_o[7:0];
        endcase
    end

    always @(*) begin
        load_half = 16'b0;
        case (byte_sel[1])
            1'b0:    load_half = mem_data_o[15: 0];
            1'b1:    load_half = mem_data_o[31:16];
            default: load_half = mem_data_o[15:0];
        endcase
    end

    always @(*) begin
        core_data_i = 32'b0; // default
        case (op_size_o)
            OP_SIZE_BYTE_S: core_data_i = {{24{load_byte[7]}}, load_byte};
            OP_SIZE_BYTE_U: core_data_i = {24'b0, load_byte};
            OP_SIZE_HALF_S: core_data_i = {{16{load_half[15]}}, load_half};
            OP_SIZE_HALF_U: core_data_i = {16'b0, load_half};
            OP_SIZE_WORD:   core_data_i = mem_data_o;
            default:         core_data_i = mem_data_o;
        endcase
    end

    // Store path: position core_data_o's low bits into addressed lane
    always @(*) begin
        mem_data_i = 32'b0; // default
        case (op_size_o[2:1])
            2'b00: begin // byte
                case (byte_sel)
                    2'b00:   mem_data_i = {24'b0, core_data_o[7:0]};
                    2'b01:   mem_data_i = {16'b0, core_data_o[7:0], 8'b0};
                    2'b10:   mem_data_i = {8'b0, core_data_o[7:0], 16'b0};
                    2'b11:   mem_data_i = {core_data_o[7:0], 24'b0};
                    default: mem_data_i = {24'b0, core_data_o[7:0]};
                endcase
            end
            2'b01: begin // half
                mem_data_i = byte_sel[1] ? {core_data_o[15:0], 16'b0}
                                          : {16'b0, core_data_o[15:0]};
            end
            2'b10: mem_data_i = core_data_o; // word
            default: mem_data_i = core_data_o;
        endcase
    end

endmodule
