// tb_top_system.v -- slice 7g final integration testbench.
//
// Runs firmware/validation.hex: one self-checking program covering the
// full RV32I set (R-type and I-type ALU, all 5 load variants, all 3
// store widths, an IMEM load, all 6 branches + a backward loop, jal/jalr
// with link-value checks, lui/auipc), all 4 Zmmul ops, and all 3 Xicrc
// chains (firmware/crc_test.S's body, hand-assembled directly), followed
// by ECALL and a self-loop. Generated by scripts/gen_validation_fw.py,
// which also independently simulates the program (scripts/rvbl2_sim.py)
// before ever touching iverilog and prints the exact predicted cycle
// count and the full check registry reproduced below.
//
// ---------------------------------------------------------------------
// PART 1 -- halt_o semantics, confirmed directly in control_unit.v before
// writing a line of firmware (task requirement):
//
//   control_unit.v:222-224 -- is_ecall = OPCODE_SYSTEM && funct3==000 &&
//     funct12==FUNCT12_ECALL.
//   control_unit.v:226-234 -- sequential, NBA, sync reset: halt_o<=1 when
//     (state==EXECUTE_ALU && is_ecall), else HELD (no clearing branch
//     anywhere but reset). Sticky, confirmed by reading the block: there
//     is no code path that ever drives halt_o back to 0 except rst_i.
//   control_unit.v's next-state logic (EXECUTE_ALU case, ~line 265-268):
//     OPCODE_SYSTEM (which covers ECALL) advances to FETCH like every
//     other instruction -- next_state is NOT gated on halt_o anywhere in
//     the file, and no output in the combinational output-logic block
//     reads halt_o either. So the FSM provably keeps fetching after
//     ECALL retires -- confirmed by inspection, not assumed.
//
// Consequence: firmware/validation.hex's `finish` label ends with
// `ecall` immediately followed by `jal x0,0` (self-loop, encoding
// 0x0000006f, confirmed round-tripped by scripts/rvbl2_decode.py) so the
// core spins in place forever after halt_o asserts instead of running
// off the end of IMEM into uninitialized (X-valued) memory, which would
// otherwise trip this very testbench's own no-X-fetch check (assertion
// 3) against its own passing firmware.
//
// ---------------------------------------------------------------------
// PART 4 (of the task) -- toolchain: scripts/rvbl2_asm.py (two-pass
// assembler, labels/branches/jal resolved in a second pass),
// scripts/rvbl2_decode.py (independent decoder, separate bitfield-
// extraction code path, used for round-trip verification), and
// scripts/rvbl2_sim.py (reference functional simulator, used to prove
// the firmware's self-checking logic reaches PASS_CODE and to derive the
// predicted cycle count below) -- see scripts/README.md. No RV32I
// assembler is on PATH in this environment (checked again this slice).
//
// ---------------------------------------------------------------------
// Field breakdowns (three representative encodings not exercised by any
// prior slice's firmware -- S-type, B-type, and a large-offset J-type):
//
//   sw x14,64(x2)  @ 0x00400200 = 0x04e12023
//     S-type: imm[11:5]=inst[31:25], rs2=inst[24:20], rs1=inst[19:15],
//             funct3=inst[14:12], imm[4:0]=inst[11:7], opcode=inst[6:0]
//     imm=64 (0b000000_1000000) -> imm[11:5]=0000010, imm[4:0]=00000
//     inst[31:25]=0000010, inst[24:20]=rs2=x14=01110,
//     inst[19:15]=rs1=x2=00010, inst[14:12]=funct3(sw)=010,
//     inst[11:7]=imm[4:0]=00000, inst[6:0]=0100011
//     = 0000010_01110_00010_010_00000_0100011 = 0x04e12023 (verified)
//
//   beq x13,x9,+16  @ 0x00400014 = 0x00968863  (implicit skip-poison
//   pattern used by every check() in the firmware -- see scripts/
//   gen_validation_fw.py's check()/check_reg() helpers)
//     B-type: imm[12]=inst[31], imm[11]=inst[7], imm[10:5]=inst[30:25],
//             imm[4:1]=inst[11:8] (imm[0] implicit 0)
//     imm=16 (0b0_000000_1000_0) -> imm[12]=0,imm[11]=0,imm[10:5]=000000,
//     imm[4:1]=1000
//     inst[31]=0, inst[30:25]=000000, inst[24:20]=rs2=x9=01001,
//     inst[19:15]=rs1=x13=01101, inst[14:12]=funct3(beq)=000,
//     inst[11:8]=1000, inst[7]=0, inst[6:0]=1100011
//     = 0000000_01001_01101_000_1000_0_1100011 = 0x00968863 (verified)
//
//   jal x0,+1608  @ 0x00400020 = 0x6480006f  (skips the FAIL_ID+jump
//   pair after a failed check 1, landing at `finish`)
//     J-type: imm[20]=inst[31], imm[19:12]=inst[19:12], imm[11]=inst[20],
//             imm[10:1]=inst[30:21] (imm[0] implicit 0)
//     imm=1608 (0d) = 0b0_0000_0110_0100_1000_0 (21-bit) ->
//     imm[20]=0, imm[19:12]=00000110, imm[11]=0, imm[10:1]=0100100000
//     inst[31]=0, inst[30:21]=0100100000, inst[20]=0,
//     inst[19:12]=00000110, inst[11:7]=rd=x0=00000, inst[6:0]=1101111
//     = 0_0100100000_0_00000110_00000_1101111 = 0x6480006f (verified)
//
// ---------------------------------------------------------------------
// Check registry (from scripts/gen_validation_fw.py's printed output --
// 46 entries; FAIL_ID = 0xFA110000 | id, except the CRC subroutine's
// three chains which use 0xFA1100B0/B1/B2):
//   [1] add 12+5                [17] srai (arith, TRAP if =srli)
//   [2] sub 12-5                [18] slti -1<1 (signed true)
//   [3] and 12&5                [19] sltiu 0xFFFFFFFF<1 (unsigned false)
//   [4] or 12|5                 [20] lw @+0x40
//   [5] xor 12^5                [21] lb @+0x40 (sign-extend)
//   [6] sll 12<<5               [22] lbu @+0x40
//   [7] srl (logical)           [23] lh @+0x40 (sign-extend)
//   [8] sra (arith, TRAP if=srl)[24] lhu @+0x40
//   [9] slt -1<1 (signed true)  [25] lb @+0x42 (nonzero byte offset)
//   [10] sltu (unsigned false)  [26] sb lane1 readback
//   [11] addi 10+5              [27] sh upper-half readback
//   [12] andi 0xA&6             [28] lw from IMEM (embedded .word)
//   [13] ori 0xA|6              [29..34] beq/bne/blt/bltu/bge/bgeu
//   [14] xori 0xA^6             [35] backward loop terminates at 0
//   [15] slli 1<<5              [36..37] jal PC-redirect + link value
//   [16] srli (logical)         [38..39] jalr PC-redirect + link value
//                                [40] lui 0x12345
//                                [41] auipc addr+0x1000
//                                [42..45] mul/mulh/mulhu/mulhsu
//                                [B0/B1/B2] crcb/crch/crcw chains
//
// Coverage: every RV32I instruction class is exercised except FENCE/
// EBREAK (slice 5's no-op cases -- not re-tested here, no new behavior
// since slice 5) and the illegal-opcode default path (policy still open
// per rvbl2_defines.vh). Zmmul (4/4) and Xicrc (3/3) fully covered.
//
// ---------------------------------------------------------------------
// Predicted cycle count: 980 (from scripts/gen_validation_fw.py's
// simulator run, summing each of the 255 actually-executed instructions'
// cost from the handoff table: R-type/I-type/MUL/CRC/JAL/JALR/LUI/AUIPC
// = 4, load = 6, store = 4, branch = 3, ECALL = 3). Computed from the
// program's real execution trace (branches taken as the firmware
// actually takes them), not read off an RTL simulation.

`timescale 1ns/1ps
`include "pkg/rvbl2_defines.vh"

module tb_top_system;

    localparam PASS_CODE  = 32'h0000C0DE;
    localparam FAIL_MARK  = 32'hFA110000;
    localparam STATUS_IDX = 64; // (DMEM_BASE+0x100)/4 -- see gen_validation_fw.py

    reg clk_i;
    reg rst_i;
    wire halt_o;

    integer errors;
    integer i;
    integer cyc;
    localparam CYCLE_BUDGET = 2000; // predicted 980 + generous margin

    wire verbose;
    assign verbose = $test$plusargs("VERBOSE");

    top #(
        .IMEM_DEPTH_WORDS (1024),
        .IMEM_INIT_FILE   ("firmware/validation.hex")
    ) dut (
        .clk_i  (clk_i),
        .rst_i  (rst_i),
        .halt_o (halt_o)
    );

    always #5 clk_i = ~clk_i;

    // Per-cycle trace, gated behind +VERBOSE so the default run stays readable.
    always @(posedge clk_i) begin
        #1;
        if (verbose)
            $display("t=%0t state=%0d pc=%h ir=%h halt_o=%b regs1=%h",
                      $time, dut.u_control_unit.state, dut.pc, dut.ir,
                      halt_o, dut.u_regfile.regs[1]);
    end

    // ------------------------------------------------------------------
    // Check 3: the core must never fetch an X instruction. Sampled at
    // DECODE (the cycle after ir_write_o latched it in FETCH), per the
    // task brief. Uninitialized IMEM reads X and propagates silently
    // through the whole datapath otherwise -- this is the only thing
    // that turns a runaway PC into a loud, immediate failure instead of
    // a confusing downstream mismatch.
    // ------------------------------------------------------------------
    always @(posedge clk_i) begin
        #1;
        if (!rst_i && dut.u_control_unit.state == dut.u_control_unit.DECODE) begin
            if (^dut.ir === 1'bx) begin
                $fatal(1, "FATAL [no-X fetch] ir is X during DECODE at t=%0t, ir=%h, pc=%h -- PC ran off the program",
                          $time, dut.ir, dut.pc);
            end
        end
    end

    // Check 4: no X ever written to the register file.
    always @(posedge clk_i) begin
        #1;
        if (!rst_i && dut.reg_write_o) begin
            if (^dut.mux_result === 1'bx) begin
                $display("FAIL [no-X write] mux_result is X at WRITE_BACK, t=%0t, pc=%h", $time, dut.pc);
                errors = errors + 1;
            end
        end
    end

    // Check 5: regs[0] stays 0 for the entire run.
    always @(*) begin
        if (!rst_i && dut.u_regfile.regs[0] !== 32'b0) begin
            $display("FAIL [x0 guard] regs[0] exp=0 got=%h, t=%0t", dut.u_regfile.regs[0], $time);
            errors = errors + 1;
        end
    end

    initial begin
        $dumpfile("sim/tb_top_system.vcd");
        $dumpvars(0, tb_top_system);

        errors = 0;
        clk_i = 0;
        rst_i = 1;

        @(posedge clk_i); #1; // RESET latched
        if (dut.u_control_unit.state !== dut.u_control_unit.RESET) begin
            $display("FAIL [reset] state exp=RESET got=%0d", dut.u_control_unit.state);
            errors = errors + 1;
        end
        if (halt_o !== 1'b0) begin
            $display("FAIL [halt_o] expected 0 immediately after reset, got %b", halt_o);
            errors = errors + 1;
        end

        rst_i = 0;
        @(posedge clk_i); #1; // RESET -> FETCH (instruction 0)

        // ------------------------------------------------------------------
        // Check 1 (halt_o stays 0) + Check 6 (cycle count) + Check 7
        // (watchdog), all in one loop: halt_o is asserted or negated by
        // this very while-condition, so a mutation that removes the
        // ECALL (never setting halt_o) hits CYCLE_BUDGET here and
        // $fatal's with an explicit message -- not a silent hang.
        // ------------------------------------------------------------------
        cyc = 0;
        while (!halt_o && cyc < CYCLE_BUDGET) begin
            @(posedge clk_i); #1;
            cyc = cyc + 1;
        end

        if (!halt_o) begin
            $fatal(1, "WATCHDOG [halt_o never asserted]: exceeded %0d cycles without ECALL retiring -- pc=%h state=%0d",
                      CYCLE_BUDGET, dut.pc, dut.u_control_unit.state);
        end

        $display("halt_o asserted after %0d cycles (predicted 980)", cyc);
        if (cyc !== 980) begin
            $display("FAIL [cycle count] exp=980 (see scripts/gen_validation_fw.py's simulator output) got=%0d", cyc);
            errors = errors + 1;
        end

        // ------------------------------------------------------------------
        // Sticky check: halt_o must stay 1 for several more cycles (the
        // self-loop keeps the FSM running harmlessly -- halt_o is a
        // status flag, not a stop signal, see PART 1 above).
        // ------------------------------------------------------------------
        for (i = 0; i < 10; i = i + 1) begin
            @(posedge clk_i); #1;
            if (halt_o !== 1'b1) begin
                $display("FAIL [halt_o sticky] dropped to %b, %0d cycles after first assertion", halt_o, i + 1);
                errors = errors + 1;
            end
        end

        // ------------------------------------------------------------------
        // Check 2: the firmware reached PASS_CODE, not a FAIL_ID. Checked
        // on both x1 and the DMEM status word (finish: stores the same
        // code to both -- see scripts/gen_validation_fw.py).
        // ------------------------------------------------------------------
        if (dut.u_regfile.regs[1] !== PASS_CODE) begin
            $display("FAIL [firmware self-check] x1=%h -- expected PASS_CODE=%h",
                      dut.u_regfile.regs[1], PASS_CODE);
            if (dut.u_regfile.regs[1][31:16] === FAIL_MARK[31:16]) begin
                $display("  FAIL_ID = 0x%h -- see tb_top_system.v's check registry / scripts/gen_validation_fw.py's CHECKS list for which check this is",
                          dut.u_regfile.regs[1] & 32'h0000FFFF);
            end else begin
                $display("  x1 does not even carry the FAIL_MARK pattern (0x%h) -- firmware may not have reached `finish` at all",
                          FAIL_MARK);
            end
            errors = errors + 1;
        end else begin
            $display("PASS [firmware self-check] x1 = PASS_CODE (0x%h)", PASS_CODE);
        end

        if (dut.u_dmem.mem[STATUS_IDX] !== dut.u_regfile.regs[1]) begin
            $display("FAIL [status DMEM word] mem[%0d]=%h does not match x1=%h",
                      STATUS_IDX, dut.u_dmem.mem[STATUS_IDX], dut.u_regfile.regs[1]);
            errors = errors + 1;
        end

        if (errors == 0)
            $display("ALL TESTS PASSED");
        else
            $display("%0d CHECK(S) FAILED", errors);

        $finish;
    end

endmodule
